name: mix format --check-formatted
description: "Runs `mix format --check-formatted`"
inputs:
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - run: mix format --check-formatted
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
