name: mix dialyzer --plt
inputs:
  mix-env:
    required: true
runs:
  using: "composite"
  steps:
    - name: Retrieve PLT Cache
      uses: actions/cache@v1
      id: plt-cache
      with:
        path: priv/plts
        key: 1-plt-${{ inputs.mix-env }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}{1}', github.workspace, '/.tool-versions')) }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - name: Create PLTs
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt
      shell: bash
