name: mix hex.audit
description: "Runs `mix hex.audit`"
inputs:
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - run: mix hex.audit
      shell: bash
      env:
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
