name: Install Elixir and Erlang
description: "Install Erlang and Elixir as per the `.tool-versions` file."
inputs:
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1
      with:
        version-file: "${{ inputs.working-directory }}/.tool-versions"
        version-type: strict
      env:
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
