name: Install Elixir and Erlang
description: "Install Erlang and Elixir as per the `.tool-versions` file."
runs:
  using: "composite"
  steps:
    - uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict
      env:
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
