name: Get ASDF tool versions
description: "Retrieves the tool versions from the .tool-versions file"
outputs:
  erlang:
    description: "The Erlang version as found within the .tool-versions file"
    value: ${{ steps.erlang.outputs.version }}
  elixir:
    description: "The Elixir version as found within the .tool-versions file"
    value: ${{ steps.elixir.outputs.version }}
inputs:
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
runs:
  using: "composite"
  steps:
    - id: erlang
      run: echo "::set-output name=version::$(grep erlang .tool-versions | cut -d ' ' -f 2)"
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
    - id: elixir
      run: echo "::set-output name=version::$(grep elixir .tool-versions | cut -d ' ' -f 2)"
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
