name: mix dialyzer --format github
description: "Runs `mix dialyzer --format github`"
inputs:
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  use-cache:
    description: "Use caches?"
    required: false
    default: "true"
  cache-prefix:
    description: "Optional prefix for the cache key"
    required: false
    default: ""
  plt-path:
    description: "The path within the workspace where the PLT files should be stored"
    required: false
    default: "priv/plts"
runs:
  using: "composite"
  steps:
    - uses: team-alembic/staple-actions/actions/mix-dialyzer-plt-composable@main
      with:
        working-directory: ${{ inputs.working-directory }}
        use-cache: ${{ inputs.use-cache }}
        cache-prefix: ${{ inputs.cache-prefix }}
        mix-env: ${{ inputs.mix-env }}
        plt-path: ${{ inputs.plt-path }}
    - run: mix dialyzer --format github
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
